export type ModalType = 'HIRE CANDIDATE' | 'PROCESS' | 'UPDATE RESULT' | 'MOVE TO ANOTHER VACANCY' | 'VIEW HISTORY' | 'BLACKLIST' | 'REJECT'

export type TableType = 'INTERVIEW' | 'ASSESSMENT' | 'OFFERING'
