export type ModalType =
  | 'BLACKLIST'
  | 'EDIT JOIN DATE'
  | 'HIRE CANDIDATE'
  | 'MOVE TO ANOTHER VACANCY'
  | 'PROCESS'
  | 'REJECT'
  | 'RESCHEDULE'
  | 'UPDATE RESULT'
  | 'VIEW HISTORY'
  | 'WITHDRAW'

export type TableType = 'ADMINISTRATION' | 'SELECTION' | 'OFFERING' | 'ONBOARDING'
